


#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CustomItemGenerator.Fields.LinkTypes;
using CustomItemGenerator.Fields.ListTypes;
using CustomItemGenerator.Fields.SimpleTypes;
using Sitecore.Data.Fields;
using Sitecore.Data.Items;
using Sitecore.Web.UI.WebControls;






namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		/// <summary>
		/// content Item
		/// <para></para>
		/// <para>Path: /sitecore/content</para>	
		/// <para>ID: 0de95ae4-41ab-4d01-9eb0-67441b7c2450</para>	
		/// </summary>
		public static partial class Content{
			public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("0de95ae4-41ab-4d01-9eb0-67441b7c2450"); } }
			public static string ItemName { get { return  "content"; } }
			public static string ItemPath { get { return  "/sitecore/content"; } }
			
			public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("e3e2d58c-df95-4230-adc9-279924cece84"); } }
			public static string TemplateName { get { return "Main section"; } }
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					public static partial class _2012{
						public static partial class _01{
							public static partial class _31{
								/// <summary>
								/// good-news Item
								/// <para></para>
								/// <para>Path: /sitecore/content/CodeGenHome/News/2012/01/31/good-news</para>	
								/// <para>ID: 10671f3c-e495-4604-9469-e24ca149ce4c</para>	
								/// </summary>
								public static partial class Good_News{
									public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("10671f3c-e495-4604-9469-e24ca149ce4c"); } }
									public static string ItemName { get { return  "good-news"; } }
									public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2012/01/31/good-news"; } }
									
									public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
									public static string TemplateName { get { return "ArticlePage"; } }
								}
							}
						}
					}
				}
			}
		}
	}
}











 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace
{
	/// <summary>
	/// ArticlePage
	/// <para></para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/ArticlePage</para>	
	/// <para>ID: 1177d05b-8ff5-45fa-b287-68c16c858cb3</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="ArticlePage{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class ArticlePage : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/ArticlePage
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "1177d05b-8ff5-45fa-b287-68c16c858cb3";

		#region Inherited Base Templates
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		private readonly global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Bases.BasePage _basePage;
        
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Bases.BasePage BasePage { get { return _basePage; } }
        #endregion

		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="ArticlePage"/> class.
		/// <code>
		/// ArticlePage articlePage = new ArticlePage(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public ArticlePage(Item innerItem) : base(innerItem)
		{
         	_basePage = new global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Bases.BasePage(innerItem);
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="ArticlePage"/> class.
		/// <code>
		/// ArticlePage articlePage = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator ArticlePage(Item innerItem)
		{
			return innerItem != null ? new ArticlePage(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(ArticlePage customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
		/// <summary>
		/// The ArticleCopy field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: a2d0706e-97d8-47b4-bb8c-ce07c0f48a5b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField ArticleCopy  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("a2d0706e-97d8-47b4-bb8c-ce07c0f48a5b")]); } }
		
		/// <summary>
		/// The ArticleTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: b1a021d2-be4d-4b60-96a5-13fd303afeb3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField ArticleTitle  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("b1a021d2-be4d-4b60-96a5-13fd303afeb3")]); } }
		
	
		#endregion
		 
	}
}






namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					/// <summary>
					/// 2012 Item
					/// <para></para>
					/// <para>Path: /sitecore/content/CodeGenHome/News/2012</para>	
					/// <para>ID: 14d45025-e942-48a9-b1e2-26a3d1a3c977</para>	
					/// </summary>
					public static partial class _2012{
						public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("14d45025-e942-48a9-b1e2-26a3d1a3c977"); } }
						public static string ItemName { get { return  "2012"; } }
						public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2012"; } }
						
						public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
						public static string TemplateName { get { return "ArticlePage"; } }
					}
				}
			}
		}
	}
}











 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases
{
	/// <summary>
	/// template with reserved word in a field
	/// <para>This sc template has a field called class.</para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/EdgeCases/template with reserved word in a field</para>	
	/// <para>ID: 1841c65a-3eee-4663-a43e-aa9d07f3b4a4</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="template with reserved word in a field{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class Template_With_Reserved_Word_In_A_Field : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/EdgeCases/template with reserved word in a field
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "1841c65a-3eee-4663-a43e-aa9d07f3b4a4";


		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="Template_With_Reserved_Word_In_A_Field"/> class.
		/// <code>
		/// Template_With_Reserved_Word_In_A_Field template_With_Reserved_Word_In_A_Field = new template with reserved word in a field(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public Template_With_Reserved_Word_In_A_Field(Item innerItem) : base(innerItem)
		{
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="Template_With_Reserved_Word_In_A_Field"/> class.
		/// <code>
		/// Template_With_Reserved_Word_In_A_Field template_With_Reserved_Word_In_A_Field = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Template_With_Reserved_Word_In_A_Field(Item innerItem)
		{
			return innerItem != null ? new Template_With_Reserved_Word_In_A_Field(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(Template_With_Reserved_Word_In_A_Field customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
		/// <summary>
		/// The class field.
		/// <para>This field is called 'class' which is a C# reserved word.</para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 92e996d5-8c27-4286-ac12-02e99b5839fc</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField Class  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("92e996d5-8c27-4286-ac12-02e99b5839fc")]); } }
		
	
		#endregion
		 
	}
}






namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class Articles{
					/// <summary>
					/// Article-1 Item
					/// <para></para>
					/// <para>Path: /sitecore/content/CodeGenHome/Articles/Article-1</para>	
					/// <para>ID: 232b953b-4bc4-428a-b597-bf2b3f7e364e</para>	
					/// </summary>
					public static partial class Article_1{
						public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("232b953b-4bc4-428a-b597-bf2b3f7e364e"); } }
						public static string ItemName { get { return  "Article-1"; } }
						public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/Articles/Article-1"; } }
						
						public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
						public static string TemplateName { get { return "ArticlePage"; } }
					}
				}
			}
		}
	}
}











 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases
{
	/// <summary>
	/// template with special char in a field
	/// <para></para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/EdgeCases/template with special char in a field</para>	
	/// <para>ID: 29953850-949d-47ba-9790-d3abcbc95564</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="template with special char in a field{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class Template_With_Special_Char_In_A_Field : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/EdgeCases/template with special char in a field
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "29953850-949d-47ba-9790-d3abcbc95564";


		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="Template_With_Special_Char_In_A_Field"/> class.
		/// <code>
		/// Template_With_Special_Char_In_A_Field template_With_Special_Char_In_A_Field = new template with special char in a field(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public Template_With_Special_Char_In_A_Field(Item innerItem) : base(innerItem)
		{
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="Template_With_Special_Char_In_A_Field"/> class.
		/// <code>
		/// Template_With_Special_Char_In_A_Field template_With_Special_Char_In_A_Field = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Template_With_Special_Char_In_A_Field(Item innerItem)
		{
			return innerItem != null ? new Template_With_Special_Char_In_A_Field(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(Template_With_Special_Char_In_A_Field customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
		/// <summary>
		/// The ñ field.
		/// <para>énye</para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: e70aaf89-857d-4d96-a6e5-1956e0a440b0</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField Ñ  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("e70aaf89-857d-4d96-a6e5-1956e0a440b0")]); } }
		
		/// <summary>
		/// The 作成したり field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 5beda2fc-c507-4305-ac31-7c9f1752c0d6</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField 作成したり  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("5beda2fc-c507-4305-ac31-7c9f1752c0d6")]); } }
		
	
		#endregion
		 
	}
}









 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Interfaces
{
	/// <summary>
	/// INavigation
	/// <para></para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/Interfaces/INavigation</para>	
	/// <para>ID: 2d639823-efd8-4e6f-b8dc-507e920fa5b4</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="INavigation{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class INavigation : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/Interfaces/INavigation
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "2d639823-efd8-4e6f-b8dc-507e920fa5b4";


		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="INavigation"/> class.
		/// <code>
		/// INavigation iNavigation = new INavigation(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public INavigation(Item innerItem) : base(innerItem)
		{
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="INavigation"/> class.
		/// <code>
		/// INavigation iNavigation = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator INavigation(Item innerItem)
		{
			return innerItem != null ? new INavigation(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(INavigation customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
		/// <summary>
		/// The NavigationHidden field.
		/// <para>Is this item hidden from auto generated menus?</para>
		/// <para>Field Type: Checkbox</para>		
		/// <para>Field ID: 88175068-c8c5-4469-80a0-e1cb0f4f6259</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomCheckboxField NavigationHidden  {get { return new CustomCheckboxField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("88175068-c8c5-4469-80a0-e1cb0f4f6259")]); } }
		
		/// <summary>
		/// The NavigationTitle field.
		/// <para>The text to use in auto generated menus</para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 213b5d36-f77a-4144-94da-0ef49ee68677</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField NavigationTitle  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("213b5d36-f77a-4144-94da-0ef49ee68677")]); } }
		
	
		#endregion
		 
	}
}






namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					/// <summary>
					/// 2011 Item
					/// <para></para>
					/// <para>Path: /sitecore/content/CodeGenHome/News/2011</para>	
					/// <para>ID: 35df3a06-4614-4c3f-bd5f-f7e462d99c03</para>	
					/// </summary>
					public static partial class _2011{
						public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("35df3a06-4614-4c3f-bd5f-f7e462d99c03"); } }
						public static string ItemName { get { return  "2011"; } }
						public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2011"; } }
						
						public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
						public static string TemplateName { get { return "ArticlePage"; } }
					}
				}
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					public static partial class _2011{
						public static partial class _01{
							/// <summary>
							/// 31 Item
							/// <para></para>
							/// <para>Path: /sitecore/content/CodeGenHome/News/2011/01/31</para>	
							/// <para>ID: 61cdafc9-75ec-4ec0-9aff-c35293ae3262</para>	
							/// </summary>
							public static partial class _31{
								public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("61cdafc9-75ec-4ec0-9aff-c35293ae3262"); } }
								public static string ItemName { get { return  "31"; } }
								public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2011/01/31"; } }
								
								public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
								public static string TemplateName { get { return "ArticlePage"; } }
							}
						}
					}
				}
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					public static partial class _2011{
						public static partial class _01{
							public static partial class _31{
								/// <summary>
								/// no-news Item
								/// <para></para>
								/// <para>Path: /sitecore/content/CodeGenHome/News/2011/01/31/no-news</para>	
								/// <para>ID: 628eef7f-bb4b-452f-8730-ab5c992675ae</para>	
								/// </summary>
								public static partial class No_News{
									public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("628eef7f-bb4b-452f-8730-ab5c992675ae"); } }
									public static string ItemName { get { return  "no-news"; } }
									public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2011/01/31/no-news"; } }
									
									public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
									public static string TemplateName { get { return "ArticlePage"; } }
								}
							}
						}
					}
				}
			}
		}
	}
}











 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases._class
{
	/// <summary>
	/// this template is in a folder called class
	/// <para>This class should be in a namespace called _class</para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/EdgeCases/class/this template is in a folder called class</para>	
	/// <para>ID: 6b008ac2-0d68-4878-b04a-3bb1e1fbf2fa</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="this template is in a folder called class{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class This_Template_Is_In_A_Folder_Called_Class : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/EdgeCases/class/this template is in a folder called class
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "6b008ac2-0d68-4878-b04a-3bb1e1fbf2fa";


		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="This_Template_Is_In_A_Folder_Called_Class"/> class.
		/// <code>
		/// This_Template_Is_In_A_Folder_Called_Class this_Template_Is_In_A_Folder_Called_Class = new this template is in a folder called class(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public This_Template_Is_In_A_Folder_Called_Class(Item innerItem) : base(innerItem)
		{
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="This_Template_Is_In_A_Folder_Called_Class"/> class.
		/// <code>
		/// This_Template_Is_In_A_Folder_Called_Class this_Template_Is_In_A_Folder_Called_Class = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator This_Template_Is_In_A_Folder_Called_Class(Item innerItem)
		{
			return innerItem != null ? new This_Template_Is_In_A_Folder_Called_Class(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(This_Template_Is_In_A_Folder_Called_Class customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
	
		#endregion
		 
	}
}









 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace
{
	/// <summary>
	/// EveryFieldSample
	/// <para>This is the Everything template. it has one every field that exists in Sitecore 6.5.0.110602</para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/EveryFieldSample</para>	
	/// <para>ID: 6e910c94-8779-4371-a2e7-49d33bdd0cdf</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="EveryFieldSample{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class EveryFieldSample : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/EveryFieldSample
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "6e910c94-8779-4371-a2e7-49d33bdd0cdf";


		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="EveryFieldSample"/> class.
		/// <code>
		/// EveryFieldSample everyFieldSample = new EveryFieldSample(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public EveryFieldSample(Item innerItem) : base(innerItem)
		{
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="EveryFieldSample"/> class.
		/// <code>
		/// EveryFieldSample everyFieldSample = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator EveryFieldSample(Item innerItem)
		{
			return innerItem != null ? new EveryFieldSample(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(EveryFieldSample customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
			//Could not find Field Type for Profile Cards
		
			//Could not find Field Type for Profile Card Value
		
			//Could not find Field Type for Tracking
		
		/// <summary>
		/// The htmlField field.
		/// <para></para>
		/// <para>Field Type: html</para>		
		/// <para>Field ID: e42b31fc-d1a1-4640-bbf3-47a5aa94e893</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField HtmlField  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("e42b31fc-d1a1-4640-bbf3-47a5aa94e893")]); } }
		
			//Could not find Field Type for link
		
		/// <summary>
		/// The lookupField field.
		/// <para></para>
		/// <para>Field Type: lookup</para>		
		/// <para>Field ID: df5a71cb-1d7a-494b-88c2-10c27fd4291f</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomLookupField LookupField  {get { return new CustomLookupField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("df5a71cb-1d7a-494b-88c2-10c27fd4291f")]); } }
		
		/// <summary>
		/// The memoField field.
		/// <para></para>
		/// <para>Field Type: memo</para>		
		/// <para>Field ID: 6a4c5408-7ab4-4524-acb3-0c6e8b562e5d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField MemoField  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("6a4c5408-7ab4-4524-acb3-0c6e8b562e5d")]); } }
		
		/// <summary>
		/// The referenceField field.
		/// <para></para>
		/// <para>Field Type: reference</para>		
		/// <para>Field ID: c739fd01-fe03-47d4-8342-ed292c53c9f3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomLookupField ReferenceField  {get { return new CustomLookupField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("c739fd01-fe03-47d4-8342-ed292c53c9f3")]); } }
		
			//Could not find Field Type for server file
		
		/// <summary>
		/// The textField field.
		/// <para></para>
		/// <para>Field Type: text</para>		
		/// <para>Field ID: 77ba6bda-98d5-45de-857a-804f826da54c</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField TextField  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("77ba6bda-98d5-45de-857a-804f826da54c")]); } }
		
		/// <summary>
		/// The treeField field.
		/// <para></para>
		/// <para>Field Type: tree</para>		
		/// <para>Field ID: 80a588dc-533a-4a74-b2f1-04b8ad125f16</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomLookupField TreeField  {get { return new CustomLookupField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("80a588dc-533a-4a74-b2f1-04b8ad125f16")]); } }
		
			//Could not find Field Type for tree list
		
			//Could not find Field Type for valuelookup
		
			//Could not find Field Type for Icon
		
			//Could not find Field Type for IFrame
		
			//Could not find Field Type for Tristate
		
		/// <summary>
		/// The DroplinkField field.
		/// <para></para>
		/// <para>Field Type: Droplink</para>		
		/// <para>Field ID: 778e9b11-8406-431c-aac3-c85161894abb</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomLookupField DroplinkField  {get { return new CustomLookupField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("778e9b11-8406-431c-aac3-c85161894abb")]); } }
		
		/// <summary>
		/// The DroptreeField field.
		/// <para></para>
		/// <para>Field Type: Droptree</para>		
		/// <para>Field ID: f3f9f7c7-42e2-4eb2-8391-4634228d7355</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomLookupField DroptreeField  {get { return new CustomLookupField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("f3f9f7c7-42e2-4eb2-8391-4634228d7355")]); } }
		
		/// <summary>
		/// The GeneralLinkField field.
		/// <para></para>
		/// <para>Field Type: General Link</para>		
		/// <para>Field ID: 15d23bf3-104e-4060-baf2-f90a82b8c2aa</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomGeneralLinkField GeneralLinkField  {get { return new CustomGeneralLinkField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("15d23bf3-104e-4060-baf2-f90a82b8c2aa")]); } }
		
			//Could not find Field Type for Version Link
		
		/// <summary>
		/// The CheckListField field.
		/// <para></para>
		/// <para>Field Type: Checklist</para>		
		/// <para>Field ID: f1c7bc47-c912-4e3a-b792-a9bbb718a1cf</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomChecklistField CheckListFields  {get { return new CustomChecklistField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("f1c7bc47-c912-4e3a-b792-a9bbb718a1cf")]); } }
		
		/// <summary>
		/// The DropListField field.
		/// <para></para>
		/// <para>Field Type: Droplist</para>		
		/// <para>Field ID: 46721d22-4f91-4a6a-9503-9b4aea4e992a</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomMultiListField DropListField  {get { return new CustomMultiListField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("46721d22-4f91-4a6a-9503-9b4aea4e992a")]); } }
		
		/// <summary>
		/// The GroupedDroplinkField field.
		/// <para></para>
		/// <para>Field Type: Grouped Droplink</para>		
		/// <para>Field ID: e3162827-1180-45f8-b6df-8c61a39ffe29</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomLookupField GroupedDroplinkField  {get { return new CustomLookupField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("e3162827-1180-45f8-b6df-8c61a39ffe29")]); } }
		
		/// <summary>
		/// The GroupedDroplistField field.
		/// <para></para>
		/// <para>Field Type: Grouped Droplist</para>		
		/// <para>Field ID: cbefe6a3-1da1-49d4-8c2c-89b2dbcff1b3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomMultiListField GroupedDroplistField  {get { return new CustomMultiListField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("cbefe6a3-1da1-49d4-8c2c-89b2dbcff1b3")]); } }
		
		/// <summary>
		/// The MultilistField field.
		/// <para></para>
		/// <para>Field Type: Multilist</para>		
		/// <para>Field ID: 94835740-cdb8-4365-9385-35e9ba44e0be</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomMultiListField MultilistFields  {get { return new CustomMultiListField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("94835740-cdb8-4365-9385-35e9ba44e0be")]); } }
		
			//Could not find Field Type for Name Lookup Value List
		
			//Could not find Field Type for Name Value List
		
			//Could not find Field Type for Treelist Descriptive
		
		/// <summary>
		/// The TreelistExField field.
		/// <para></para>
		/// <para>Field Type: TreelistEx</para>		
		/// <para>Field ID: 9ab79881-e9c1-4ab0-b91e-e5da991afacb</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTreeListField TreelistExFields  {get { return new CustomTreeListField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("9ab79881-e9c1-4ab0-b91e-e5da991afacb")]); } }
		
		/// <summary>
		/// The TreelistField field.
		/// <para></para>
		/// <para>Field Type: Treelist</para>		
		/// <para>Field ID: cea1b613-4b7b-4977-a3fe-a13e5a7eb718</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTreeListField TreelistFields  {get { return new CustomTreeListField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("cea1b613-4b7b-4977-a3fe-a13e5a7eb718")]); } }
		
		/// <summary>
		/// The CheckboxField field.
		/// <para></para>
		/// <para>Field Type: Checkbox</para>		
		/// <para>Field ID: afa9bbb9-d07d-438e-bbc8-764a17aac903</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomCheckboxField CheckboxField  {get { return new CustomCheckboxField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("afa9bbb9-d07d-438e-bbc8-764a17aac903")]); } }
		
		/// <summary>
		/// The DateField field.
		/// <para></para>
		/// <para>Field Type: Date</para>		
		/// <para>Field ID: 5e71ee65-c875-49c6-9331-69e73e6d2121</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomDateField DateField  {get { return new CustomDateField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("5e71ee65-c875-49c6-9331-69e73e6d2121")]); } }
		
		/// <summary>
		/// The DateTimeField field.
		/// <para></para>
		/// <para>Field Type: Datetime</para>		
		/// <para>Field ID: e44d4177-6aa7-4d5f-b63f-11cc663fc2a4</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomDateField DateTimeField  {get { return new CustomDateField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("e44d4177-6aa7-4d5f-b63f-11cc663fc2a4")]); } }
		
		/// <summary>
		/// The FileField field.
		/// <para></para>
		/// <para>Field Type: File</para>		
		/// <para>Field ID: 1c850734-fcb5-4d7c-8b91-0dbeb6b4298d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomFileField FileField  {get { return new CustomFileField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("1c850734-fcb5-4d7c-8b91-0dbeb6b4298d")]); } }
		
		/// <summary>
		/// The ImageField field.
		/// <para></para>
		/// <para>Field Type: Image</para>		
		/// <para>Field ID: 7074707b-6c64-4226-89ed-0b76e8c450d7</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomImageField ImageField  {get { return new CustomImageField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("7074707b-6c64-4226-89ed-0b76e8c450d7")]); } }
		
		/// <summary>
		/// The IntegerField field.
		/// <para></para>
		/// <para>Field Type: Integer</para>		
		/// <para>Field ID: c93af429-a977-485a-a6cd-6e3a7faade6c</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomIntegerField IntegerField  {get { return new CustomIntegerField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("c93af429-a977-485a-a6cd-6e3a7faade6c")]); } }
		
		/// <summary>
		/// The MultiLineTextField field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 7a89c8a7-de84-440c-b174-8167eba53ec6</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField MultiLineTextField  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("7a89c8a7-de84-440c-b174-8167eba53ec6")]); } }
		
		/// <summary>
		/// The NumberField field.
		/// <para></para>
		/// <para>Field Type: Number</para>		
		/// <para>Field ID: df6849b3-94e5-4f12-97ed-57132f9d03ff</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomIntegerField NumberField  {get { return new CustomIntegerField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("df6849b3-94e5-4f12-97ed-57132f9d03ff")]); } }
		
			//Could not find Field Type for Password
		
		/// <summary>
		/// The RichTextField field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: f1bef833-78ec-4bd9-806f-379b327797ed</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField RichTextField  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("f1bef833-78ec-4bd9-806f-379b327797ed")]); } }
		
		/// <summary>
		/// The SingleLineTextField field.
		/// <para>This is a single line text box field (this content comes from short description in Sitecore)</para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: d5577408-89bc-49c1-881e-d4542627b2eb</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField SingleLineTextField  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("d5577408-89bc-49c1-881e-d4542627b2eb")]); } }
		
			//Could not find Field Type for Word Document
		
			//Could not find Field Type for Attachment
		
			//Could not find Field Type for Custom
		
			//Could not find Field Type for Datasource
		
			//Could not find Field Type for File Drop Area
		
			//Could not find Field Type for Internal Link
		
			//Could not find Field Type for Layout
		
			//Could not find Field Type for Rules
		
			//Could not find Field Type for Security
		
			//Could not find Field Type for Template Field Source
		
			//Could not find Field Type for Thumbnail
		
	
		#endregion
		 
	}
}









 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Interfaces
{
	/// <summary>
	/// IMetadata
	/// <para></para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/Interfaces/IMetadata</para>	
	/// <para>ID: 6fe874a1-bfcc-4f47-9ff3-2dc818888aaf</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="IMetadata{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class IMetadata : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/Interfaces/IMetadata
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "6fe874a1-bfcc-4f47-9ff3-2dc818888aaf";


		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="IMetadata"/> class.
		/// <code>
		/// IMetadata iMetadata = new IMetadata(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public IMetadata(Item innerItem) : base(innerItem)
		{
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="IMetadata"/> class.
		/// <code>
		/// IMetadata iMetadata = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator IMetadata(Item innerItem)
		{
			return innerItem != null ? new IMetadata(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(IMetadata customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
		/// <summary>
		/// The MetaDescription field.
		/// <para>The text to use in the description meta tag</para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 163b2d96-8cc9-437e-9478-0cc8631639dd</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField MetaDescription  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("163b2d96-8cc9-437e-9478-0cc8631639dd")]); } }
		
		/// <summary>
		/// The MetaKeywords field.
		/// <para>The text to use in the keywords meta tag</para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: d8c4aff5-d664-402d-91d1-fe5d23c5f3d9</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField MetaKeywords  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("d8c4aff5-d664-402d-91d1-fe5d23c5f3d9")]); } }
		
		/// <summary>
		/// The MetaTitle field.
		/// <para>The text that appers in the browser title bar</para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 635f1db0-874b-47ce-8746-1cca9a2518c4</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField MetaTitle  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("635f1db0-874b-47ce-8746-1cca9a2518c4")]); } }
		
	
		#endregion
		 
	}
}






namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					public static partial class _2012{
						public static partial class _01{
							/// <summary>
							/// 31 Item
							/// <para></para>
							/// <para>Path: /sitecore/content/CodeGenHome/News/2012/01/31</para>	
							/// <para>ID: 7f7c8cd7-cbb7-450e-b6a6-a7aa0819c2a0</para>	
							/// </summary>
							public static partial class _31{
								public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("7f7c8cd7-cbb7-450e-b6a6-a7aa0819c2a0"); } }
								public static string ItemName { get { return  "31"; } }
								public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2012/01/31"; } }
								
								public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
								public static string TemplateName { get { return "ArticlePage"; } }
							}
						}
					}
				}
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					public static partial class _2011{
						/// <summary>
						/// 01 Item
						/// <para></para>
						/// <para>Path: /sitecore/content/CodeGenHome/News/2011/01</para>	
						/// <para>ID: 88d59687-25b9-42b0-9263-0ff8260e3b16</para>	
						/// </summary>
						public static partial class _01{
							public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("88d59687-25b9-42b0-9263-0ff8260e3b16"); } }
							public static string ItemName { get { return  "01"; } }
							public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2011/01"; } }
							
							public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
							public static string TemplateName { get { return "ArticlePage"; } }
						}
					}
				}
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				/// <summary>
				/// * Item
				/// <para></para>
				/// <para>Path: /sitecore/content/CodeGenHome/*</para>	
				/// <para>ID: 8faad21c-f36f-4320-a59f-dd2f456814df</para>	
				/// </summary>
				public static partial class Wildcard{
					public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("8faad21c-f36f-4320-a59f-dd2f456814df"); } }
					public static string ItemName { get { return  "*"; } }
					public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/*"; } }
					
					public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
					public static string TemplateName { get { return "ArticlePage"; } }
				}
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					public static partial class _2012{
						/// <summary>
						/// 01 Item
						/// <para></para>
						/// <para>Path: /sitecore/content/CodeGenHome/News/2012/01</para>	
						/// <para>ID: 9012944b-e024-4fa5-a0e4-4e4fde6f27fa</para>	
						/// </summary>
						public static partial class _01{
							public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("9012944b-e024-4fa5-a0e4-4e4fde6f27fa"); } }
							public static string ItemName { get { return  "01"; } }
							public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2012/01"; } }
							
							public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
							public static string TemplateName { get { return "ArticlePage"; } }
						}
					}
				}
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				/// <summary>
				/// News Item
				/// <para></para>
				/// <para>Path: /sitecore/content/CodeGenHome/News</para>	
				/// <para>ID: 98bd52c3-84dc-4a6e-b346-2620e049e9d5</para>	
				/// </summary>
				public static partial class News{
					public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("98bd52c3-84dc-4a6e-b346-2620e049e9d5"); } }
					public static string ItemName { get { return  "News"; } }
					public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News"; } }
					
					public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
					public static string TemplateName { get { return "ArticlePage"; } }
				}
			}
		}
	}
}











 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace
{
	/// <summary>
	/// HomePage
	/// <para></para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/HomePage</para>	
	/// <para>ID: 9c83fc44-fd30-406c-b482-8d00eb0d5fda</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="HomePage{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class HomePage : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/HomePage
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "9c83fc44-fd30-406c-b482-8d00eb0d5fda";

		#region Inherited Base Templates
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		private readonly global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Bases.BasePage _basePage;
        
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Bases.BasePage BasePage { get { return _basePage; } }
        #endregion

		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="HomePage"/> class.
		/// <code>
		/// HomePage homePage = new HomePage(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public HomePage(Item innerItem) : base(innerItem)
		{
         	_basePage = new global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Bases.BasePage(innerItem);
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="HomePage"/> class.
		/// <code>
		/// HomePage homePage = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator HomePage(Item innerItem)
		{
			return innerItem != null ? new HomePage(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(HomePage customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
		/// <summary>
		/// The FeaturedArticles field.
		/// <para></para>
		/// <para>Field Type: TreelistEx</para>		
		/// <para>Field ID: c1c90024-01af-45f8-8b40-7341f348e5da</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTreeListField FeaturedArticles  {get { return new CustomTreeListField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("c1c90024-01af-45f8-8b40-7341f348e5da")]); } }
		
	
		#endregion
		 
	}
}









 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Bases
{
	/// <summary>
	/// BasePage
	/// <para></para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/Bases/BasePage</para>	
	/// <para>ID: b0005f05-ba92-480b-b5da-65ac89e15af7</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="BasePage{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class BasePage : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/Bases/BasePage
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "b0005f05-ba92-480b-b5da-65ac89e15af7";

		#region Inherited Base Templates
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		private readonly global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Interfaces.IMetadata _iMetadata;
        
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Interfaces.IMetadata IMetadata { get { return _iMetadata; } }
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		private readonly global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Interfaces.INavigation _iNavigation;
        
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Interfaces.INavigation INavigation { get { return _iNavigation; } }
        #endregion

		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="BasePage"/> class.
		/// <code>
		/// BasePage basePage = new BasePage(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public BasePage(Item innerItem) : base(innerItem)
		{
         	_iMetadata = new global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Interfaces.IMetadata(innerItem);
         	_iNavigation = new global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.Interfaces.INavigation(innerItem);
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="BasePage"/> class.
		/// <code>
		/// BasePage basePage = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator BasePage(Item innerItem)
		{
			return innerItem != null ? new BasePage(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(BasePage customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
	
		#endregion
		 
	}
}









 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases
{
	/// <summary>
	/// template with all edge cases as a base
	/// <para></para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/EdgeCases/template with all edge cases as a base</para>	
	/// <para>ID: bad63cb2-00a0-44a6-8abb-15070107b243</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="template with all edge cases as a base{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class Template_With_All_Edge_Cases_As_A_Base : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/EdgeCases/template with all edge cases as a base
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "bad63cb2-00a0-44a6-8abb-15070107b243";

		#region Inherited Base Templates
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		private readonly global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases.spaces in name template _spaces_In_Name_Template;
        
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases.spaces in name template Spaces_In_Name_Template { get { return _spaces_In_Name_Template; } }
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		private readonly global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases.template with reserved word in a field _template_With_Reserved_Word_In_A_Field;
        
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases.template with reserved word in a field Template_With_Reserved_Word_In_A_Field { get { return _template_With_Reserved_Word_In_A_Field; } }
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		private readonly global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases.template with special char in a field _template_With_Special_Char_In_A_Field;
        
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases.template with special char in a field Template_With_Special_Char_In_A_Field { get { return _template_With_Special_Char_In_A_Field; } }
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		private readonly global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases._class.this template is in a folder called class _this_Template_Is_In_A_Folder_Called_Class;
        
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases._class.this template is in a folder called class This_Template_Is_In_A_Folder_Called_Class { get { return _this_Template_Is_In_A_Folder_Called_Class; } }
        #endregion

		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="Template_With_All_Edge_Cases_As_A_Base"/> class.
		/// <code>
		/// Template_With_All_Edge_Cases_As_A_Base template_With_All_Edge_Cases_As_A_Base = new template with all edge cases as a base(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public Template_With_All_Edge_Cases_As_A_Base(Item innerItem) : base(innerItem)
		{
         	_spaces_In_Name_Template = new global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases.spaces in name template(innerItem);
         	_template_With_Reserved_Word_In_A_Field = new global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases.template with reserved word in a field(innerItem);
         	_template_With_Special_Char_In_A_Field = new global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases.template with special char in a field(innerItem);
         	_this_Template_Is_In_A_Folder_Called_Class = new global::HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases._class.this template is in a folder called class(innerItem);
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="Template_With_All_Edge_Cases_As_A_Base"/> class.
		/// <code>
		/// Template_With_All_Edge_Cases_As_A_Base template_With_All_Edge_Cases_As_A_Base = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Template_With_All_Edge_Cases_As_A_Base(Item innerItem)
		{
			return innerItem != null ? new Template_With_All_Edge_Cases_As_A_Base(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(Template_With_All_Edge_Cases_As_A_Base customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
	
		#endregion
		 
	}
}









 

namespace HedgehogDevelopment.CodeGeneration.SampleLibrary.TemplateFolderNamespace.EdgeCases
{
	/// <summary>
	/// spaces in name template
	/// <para></para>
	/// <para>Path: /sitecore/templates/TDSCodeGen/EdgeCases/spaces in name template</para>	
	/// <para>ID: c7fa5e8e-1ec9-4019-8fbb-124bf4f6271a</para>	
	/// </summary>
	/// <remarks> 
    /// This example shows how to specify the <see cref="spaces in name template{T}"/> type as a cref attribute.
    /// </remarks>
	public partial class Spaces_In_Name_Template : global::Sitecore.Data.Items.CustomItem
	{
		/// <summary>
		/// The Template ID for /sitecore/templates/TDSCodeGen/EdgeCases/spaces in name template
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static readonly string TemplateId = "c7fa5e8e-1ec9-4019-8fbb-124bf4f6271a";


		#region Boilerplate CustomItem Code

		/// <example>
		/// This sample should how to get an instance of the <see cref="Spaces_In_Name_Template"/> class.
		/// <code>
		/// Spaces_In_Name_Template spaces_In_Name_Template = new spaces in name template(Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public Spaces_In_Name_Template(Item innerItem) : base(innerItem)
		{
		}

		/// <example>
		/// This sample should how to get an instance of the <see cref="Spaces_In_Name_Template"/> class.
		/// <code>
		/// Spaces_In_Name_Template spaces_In_Name_Template = Sitecore.Context.Item;
		/// </code>
		/// </example>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Spaces_In_Name_Template(Item innerItem)
		{
			return innerItem != null ? new Spaces_In_Name_Template(innerItem) : null;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public static implicit operator Item(Spaces_In_Name_Template customItem)
		{
			return customItem != null ? customItem.InnerItem : null;
		}

		#endregion //Boilerplate CustomItem Code

 		#region Field Instance Methods
		/// <summary>
		/// The spaces in name field field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 3ccb4d43-b227-419f-9e21-746b7ebe96d9</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - Velir.tt", "1.0")]
		public CustomTextField Spaces_In_Name_Field  {get { return new CustomTextField(InnerItem, InnerItem.Fields[new global::Sitecore.Data.ID("3ccb4d43-b227-419f-9e21-746b7ebe96d9")]); } }
		
	
		#endregion
		 
	}
}






namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					public static partial class _2011{
						public static partial class _01{
							public static partial class _31{
								/// <summary>
								/// good-news Item
								/// <para></para>
								/// <para>Path: /sitecore/content/CodeGenHome/News/2011/01/31/good-news</para>	
								/// <para>ID: cc0a9a83-8007-4dcf-9586-1e0f1bcd4efe</para>	
								/// </summary>
								public static partial class Good_News{
									public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("cc0a9a83-8007-4dcf-9586-1e0f1bcd4efe"); } }
									public static string ItemName { get { return  "good-news"; } }
									public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2011/01/31/good-news"; } }
									
									public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
									public static string TemplateName { get { return "ArticlePage"; } }
								}
							}
						}
					}
				}
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				/// <summary>
				/// Articles Item
				/// <para></para>
				/// <para>Path: /sitecore/content/CodeGenHome/Articles</para>	
				/// <para>ID: da45e6a7-bf13-4c0e-bc0f-ed1ebe6e2daa</para>	
				/// </summary>
				public static partial class Articles{
					public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("da45e6a7-bf13-4c0e-bc0f-ed1ebe6e2daa"); } }
					public static string ItemName { get { return  "Articles"; } }
					public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/Articles"; } }
					
					public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
					public static string TemplateName { get { return "ArticlePage"; } }
				}
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			/// <summary>
			/// CodeGenHome Item
			/// <para></para>
			/// <para>Path: /sitecore/content/CodeGenHome</para>	
			/// <para>ID: dbfae0cc-9f72-433c-ad0b-56a8a6d58639</para>	
			/// </summary>
			public static partial class CodeGenHome{
				public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("dbfae0cc-9f72-433c-ad0b-56a8a6d58639"); } }
				public static string ItemName { get { return  "CodeGenHome"; } }
				public static string ItemPath { get { return  "/sitecore/content/CodeGenHome"; } }
				
				public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("9c83fc44-fd30-406c-b482-8d00eb0d5fda"); } }
				public static string TemplateName { get { return "HomePage"; } }
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class News{
					public static partial class _2012{
						public static partial class _01{
							public static partial class _31{
								/// <summary>
								/// no-news Item
								/// <para></para>
								/// <para>Path: /sitecore/content/CodeGenHome/News/2012/01/31/no-news</para>	
								/// <para>ID: eaf7c745-a973-4ff8-8b3d-5841212a04a4</para>	
								/// </summary>
								public static partial class No_News{
									public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("eaf7c745-a973-4ff8-8b3d-5841212a04a4"); } }
									public static string ItemName { get { return  "no-news"; } }
									public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/News/2012/01/31/no-news"; } }
									
									public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
									public static string TemplateName { get { return "ArticlePage"; } }
								}
							}
						}
					}
				}
			}
		}
	}
}








namespace HedgehogDevelopment.CodeGeneration.SampleLibrary
{
	public static partial class ItemTree{	
		public static partial class Content{
			public static partial class CodeGenHome{
				public static partial class Articles{
					/// <summary>
					/// Article-2 Item
					/// <para></para>
					/// <para>Path: /sitecore/content/CodeGenHome/Articles/Article-2</para>	
					/// <para>ID: ff2216b6-2b31-44c1-8e15-bc2b10ba3f02</para>	
					/// </summary>
					public static partial class Article_2{
						public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID("ff2216b6-2b31-44c1-8e15-bc2b10ba3f02"); } }
						public static string ItemName { get { return  "Article-2"; } }
						public static string ItemPath { get { return  "/sitecore/content/CodeGenHome/Articles/Article-2"; } }
						
						public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("1177d05b-8ff5-45fa-b287-68c16c858cb3"); } }
						public static string TemplateName { get { return "ArticlePage"; } }
					}
				}
			}
		}
	}
}



